services:
  - type: web
    name: certificacionhhgg-web
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: redis
      - key: SESSION_DRIVER
        value: redis
